import { Fingerprint, KeyRound, Laptop, RefreshCw, ShieldCheck, Trash2 } from "lucide-react"
import { useEffect, useState } from "react"
import { useAuth } from "../context/AuthContext"
import "../styles/account-security.css"

type Session={session_id:string;created_at:string;expires_at:string;revoked_at:string|null;device_name:string|null;ip_address:string|null;last_seen_at:string|null}
export const sessionState=(session:Session)=>session.revoked_at?"Revoked":new Date(session.expires_at)<=new Date()?"Expired":"Active"
const API=import.meta.env.VITE_API_BASE_URL??"/api"
export default function AccountSecurityPage(){const {sessionToken,administrator}=useAuth();const [sessions,setSessions]=useState<Session[]>([]);const [secret,setSecret]=useState("");const [code,setCode]=useState("");const [message,setMessage]=useState("");const headers={"Content-Type":"application/json","X-Admin-Pin":sessionToken??""}
 const load=async()=>{const response=await fetch(`${API}/auth/sessions`,{headers});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Unable to load sessions.");setSessions(body.sessions)}
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[sessionToken])
 const enroll=async()=>{const response=await fetch(`${API}/auth/mfa/enroll`,{method:"POST",headers});const body=await response.json();if(!response.ok){setMessage(body.detail);return}setSecret(body.secret);setMessage("Add this secret to your authenticator, then confirm the six-digit code.")}
 const confirm=async()=>{const response=await fetch(`${API}/auth/mfa/confirm`,{method:"POST",headers,body:JSON.stringify({code})});const body=await response.json();if(!response.ok){setMessage(body.detail);return}setSecret("");setCode("");setMessage("Multi-factor authentication enabled.")}
 const revoke=async(id:string)=>{await fetch(`${API}/auth/sessions/${id}`,{method:"DELETE",headers});setMessage("Device session revoked.");await load()}
 return <main className="account-security-page"><section className="account-security-hero"><div><p><ShieldCheck size={15}/> Operator protection</p><h1>Account Security</h1><span>Protect {administrator?.email} with MFA and review signed-in devices.</span></div><button onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></section>{message&&<p className="account-security-message">{message}</p>}<section className="account-security-grid"><article><header><Fingerprint/><div><strong>Authenticator MFA</strong><small>{administrator?.mfa_enabled?"Enabled":"Enrollment available"}</small></div></header><p>Require a time-based six-digit code after password verification.</p>{!secret?<button onClick={()=>void enroll()}><KeyRound size={16}/> {administrator?.mfa_enabled?"Replace authenticator":"Set up MFA"}</button>:<div className="mfa-enrollment"><label>One-time setup secret<code>{secret}</code></label><label>Six-digit code<input inputMode="numeric" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,""))}/></label><button disabled={code.length!==6} onClick={()=>void confirm()}>Confirm MFA</button></div>}</article><article><header><KeyRound/><div><strong>Password lifecycle</strong><small>Automatic expiration</small></div></header><p>Expires: {administrator?.password_expires_at?new Date(administrator.password_expires_at).toLocaleString():"Not recorded"}</p><span className="security-note">Password resets revoke every active session.</span></article></section><section className="sessions-panel"><header><Laptop/><div><strong>Device and session inventory</strong><small>{sessions.length} recorded sessions</small></div></header>{sessions.map(session=><article key={session.session_id}><div><strong>{session.device_name||"Unknown device"}</strong><small>{session.ip_address||"Unknown address"} · created {new Date(session.created_at).toLocaleString()}</small></div><span className={`session-state ${sessionState(session).toLowerCase()}`}>{sessionState(session)}</span>{!session.revoked_at&&<button onClick={()=>void revoke(session.session_id)}><Trash2 size={15}/> Revoke</button>}</article>)}</section></main>}
