import { Cable, FlaskConical, Network, RefreshCw, Save, ShieldOff } from "lucide-react"
import { useEffect, useState } from "react"
import { Navigate } from "react-router-dom"
import { useAuth } from "../context/AuthContext"
import "../styles/agent-adapters.css"

type Manifest={adapter_id:string;protocol:string;inbound_only:boolean;network_egress:boolean;arbitrary_code:boolean;credential_storage:boolean;requires_registered_agent:boolean;allowed_actions:string[]}
export type Adapter={adapter_id:string;name:string;protocol:string;description:string;enabled:boolean;owner:string|null;purpose:string|null;allowed_actions:string[];updated_at:string;updated_by:string;manifest:Manifest}
type Overview={adapters:Adapter[];disabled_by_default:boolean;network_egress:boolean}
const API=import.meta.env.VITE_API_BASE_URL??"/api"
export const adapterStateLabel=(enabled:boolean)=>enabled?"Enabled":"Kill switch active"

export default function AgentAdaptersPage(){
 const {sessionToken,administrator}=useAuth();const [data,setData]=useState<Overview|null>(null);const [drafts,setDrafts]=useState<Record<string,Adapter>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState("");const headers={"Content-Type":"application/json","X-Admin-Pin":sessionToken??""}
 const load=async()=>{const response=await fetch(`${API}/adapters`,{headers});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Unable to load adapters.");setData(body);setDrafts(Object.fromEntries((body.adapters as Adapter[]).map(item=>[item.adapter_id,{...item,allowed_actions:[...item.allowed_actions]}]))) }
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[sessionToken])
 const patch=(id:string,value:Partial<Adapter>)=>setDrafts(current=>({...current,[id]:{...current[id],...value}}))
 const save=async(item:Adapter)=>{setBusy(item.adapter_id);setMessage("");try{const response=await fetch(`${API}/adapters/${item.adapter_id}`,{method:"PUT",headers,body:JSON.stringify({enabled:item.enabled,owner:item.owner??"",purpose:item.purpose??"",allowed_actions:item.allowed_actions})});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Adapter update failed.");setMessage(`${item.name} configuration saved.`);await load()}catch(error){setMessage(error instanceof Error?error.message:"Request failed.")}finally{setBusy("")}}
 const test=async(item:Adapter)=>{setBusy(item.adapter_id);try{const response=await fetch(`${API}/adapters/${item.adapter_id}/test`,{method:"POST",headers});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Adapter test failed.");setMessage(`${item.name} isolated test passed — no network or persistent request used.`)}catch(error){setMessage(error instanceof Error?error.message:"Test failed.")}finally{setBusy("")}}
 if(administrator?.role!=="PLATFORM_ADMIN")return <Navigate to="/dashboard" replace/>
 return <main className="adapters-page"><section className="adapters-hero"><div><p><Network size={15}/> Controlled integrations</p><h1>Agent Adapters</h1><span>Review capability manifests, test translations, and stop integrations immediately.</span></div><button onClick={()=>void load()}><RefreshCw size={17}/> Refresh</button></section>
 <section className="adapter-boundary"><ShieldOff/><div><strong>Fail-closed boundary</strong><span>Adapters are disabled by default. No adapter receives network egress, arbitrary-code access, or credential storage.</span></div></section>{message&&<p className="adapter-message">{message}</p>}
 <section className="adapter-grid">{Object.values(drafts).map(item=><article key={item.adapter_id}><header><span className="adapter-icon"><Cable/></span><div><strong>{item.name}</strong><small>{item.protocol} · {item.adapter_id}</small></div><span className={item.enabled?"state enabled":"state disabled"}>{adapterStateLabel(item.enabled)}</span></header><p>{item.description}</p><div className="manifest"><strong>Capability manifest</strong><span>Inbound only: Yes</span><span>Network egress: No</span><span>Arbitrary code: No</span><span>Credentials stored: No</span><span>Registered agent required: Yes</span></div><label>Responsible owner<input value={item.owner??""} onChange={event=>patch(item.adapter_id,{owner:event.target.value})} placeholder="Security Engineering"/></label><label>Purpose statement<textarea value={item.purpose??""} onChange={event=>patch(item.adapter_id,{purpose:event.target.value})} placeholder="Describe the approved integration purpose"/></label><fieldset><legend>Allowed actions</legend>{item.manifest.allowed_actions.map(action=><label key={action}><input type="checkbox" checked={item.allowed_actions.includes(action)} onChange={event=>patch(item.adapter_id,{allowed_actions:event.target.checked?[...item.allowed_actions,action]:item.allowed_actions.filter(value=>value!==action)})}/>{action}</label>)}</fieldset><label className="adapter-toggle"><input type="checkbox" checked={item.enabled} onChange={event=>patch(item.adapter_id,{enabled:event.target.checked})}/><span>{item.enabled?"Adapter enabled":"Emergency kill switch active"}</span></label><footer><button className="test" disabled={busy===item.adapter_id} onClick={()=>void test(item)}><FlaskConical size={15}/> Isolated test</button><button disabled={busy===item.adapter_id} onClick={()=>void save(item)}><Save size={15}/> Save controls</button></footer></article>)}</section>{!data&&<p className="adapter-loading">Loading adapter controls…</p>}</main>
}
