import {GlobeLock,Power,RefreshCw,ShieldCheck} from "lucide-react"
import {useEffect,useState} from "react"
import {Navigate} from "react-router-dom"
import {useAuth} from "../context/AuthContext"
import {useToast} from "../context/ToastContext"
import "../styles/defensive-integrations.css"
const API=import.meta.env.VITE_API_BASE_URL??"/api"
type Connector={connector_id:string;name:string;owner:string;enabled:boolean;visible_indicator:boolean;domains:string[];purpose:string}
type ResponsePlan={response_id:string;action:string;target:string;reason:string;status:string;expires_at:string;evidence_preserved:boolean}
type Data={browser_connectors:Connector[];responses:ResponsePlan[];hack_back:boolean}
export const responseTone=(status:string)=>status==="APPROVED"?"approved":status==="PENDING_APPROVAL"?"pending":"closed"
export default function DefensiveIntegrationsPage(){const {sessionToken,administrator}=useAuth();const {pushToast}=useToast();const [data,setData]=useState<Data|null>(null);const headers={"Content-Type":"application/json","X-Admin-Pin":sessionToken??""};const load=async()=>{const r=await fetch(`${API}/defensive-integrations`,{headers});if(r.ok)setData(await r.json())};useEffect(()=>{void load()},[sessionToken]);const toggle=async(item:Connector)=>{const r=await fetch(`${API}/defensive-integrations/browser-connectors/${item.connector_id}`,{method:"PUT",headers,body:JSON.stringify({enabled:!item.enabled})});const body=await r.json();pushToast({tone:r.ok?"success":"error",title:r.ok?"Connector updated":"Change blocked",message:r.ok?"The connector state was recorded.":body.detail});if(r.ok)await load()};const approve=async(item:ResponsePlan)=>{const r=await fetch(`${API}/defensive-integrations/responses/${item.response_id}/approve`,{method:"POST",headers});const body=await r.json();pushToast({tone:r.ok?"success":"error",title:r.ok?"Response approved":"Approval blocked",message:r.ok?"Controlled-adapter execution may now proceed.":body.detail});if(r.ok)await load()};if(administrator?.role!=="PLATFORM_ADMIN")return <Navigate to="/dashboard" replace/>;return <main className="defensive-page"><section className="defensive-hero"><div><span><ShieldCheck size={15}/>Human-approved and reversible</span><h1>Defensive integrations</h1><p>Permissioned browser connectors and expiring defensive response plans.</p></div><button onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button></section><section className="no-retaliation"><strong>Hack-back and irreversible retaliation are unavailable.</strong><span>Every response preserves evidence, expires automatically and requires recovery.</span></section><section className="defensive-grid"><article><h2><GlobeLock/>Browser connectors</h2>{data?.browser_connectors.map(item=><div className="defensive-row" key={item.connector_id}><span><strong>{item.name}</strong><small>{item.domains.join(", ")} · visible indicator</small></span><b>{item.enabled?"CONNECTED":"DISCONNECTED"}</b><button onClick={()=>confirm("Change this connector state?")&&void toggle(item)}><Power size={14}/></button></div>)}</article><article><h2><ShieldCheck/>Defensive responses</h2>{data?.responses.map(item=><div className="response-card" key={item.response_id}><header><strong>{item.action.replaceAll("_"," ")}</strong><b className={responseTone(item.status)}>{item.status.replaceAll("_"," ")}</b></header><span>{item.target} · expires {new Date(item.expires_at).toLocaleString()}</span><p>{item.reason}</p>{item.status==="PENDING_APPROVAL"&&<button onClick={()=>confirm("Approve this expiring defensive response?")&&void approve(item)}>Approve response</button>}</div>)}</article></section></main>}
