import { Building2, KeyRound, RefreshCw, ShieldAlert, ShieldCheck, UsersRound } from "lucide-react"
import { useEffect, useState } from "react"
import { Navigate } from "react-router-dom"
import { useAuth } from "../context/AuthContext"
import "../styles/enterprise-identity.css"

const API=import.meta.env.VITE_API_BASE_URL??"/api"
type Overview={summary:{providers:number;workload_identities:number;pending_elevations:number;active_break_glass:number};providers:Array<{provider_id:string;name:string;issuer:string;enabled:boolean;allowed_domains:string[]}>;mappings:Array<{mapping_id:string;claim_name:string;claim_value:string;greyguard_role:string}>;workloads:Array<{workload_id:string;name:string;subject:string;status:string;expires_at:string}>;elevations:Array<{elevation_id:string;requested_role:string;reason:string;status:string;expires_at:string}>}
export const enterprisePosture=(summary:Overview["summary"])=>(summary.active_break_glass>0?"Emergency access active":summary.pending_elevations>0?"Approval required":"Controlled")

export default function EnterpriseIdentityPage(){const {sessionToken,administrator}=useAuth();const [data,setData]=useState<Overview|null>(null);const [message,setMessage]=useState("");const [provider,setProvider]=useState({name:"Microsoft Entra ID",issuer:"https://login.microsoftonline.com/tenant/v2.0",client_id:"",allowed_domains:""});const headers={"Content-Type":"application/json","X-Admin-Pin":sessionToken??""}
 const load=async()=>{const response=await fetch(`${API}/enterprise-identity`,{headers});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Unable to load enterprise identity controls.");setData(body)}
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[sessionToken])
 const saveProvider=async()=>{const response=await fetch(`${API}/enterprise-identity/providers`,{method:"POST",headers,body:JSON.stringify({...provider,allowed_domains:provider.allowed_domains.split(",").map(item=>item.trim()).filter(Boolean),enabled:true})});const body=await response.json();if(!response.ok){setMessage(body.detail);return}setMessage("Identity provider configuration saved. Client secrets remain outside GreyGuard.");await load()}
 const decide=async(id:string,approved:boolean)=>{const response=await fetch(`${API}/enterprise-identity/elevations/${id}/decision`,{method:"POST",headers,body:JSON.stringify({approved})});const body=await response.json();setMessage(response.ok?`Elevation ${approved?"approved":"rejected"}.`:body.detail);await load()}
 if(administrator?.role!=="PLATFORM_ADMIN")return <Navigate to="/dashboard" replace/>
 return <main className="enterprise-identity-page"><section className="enterprise-identity-hero"><div><p><Building2 size={15}/> Enterprise trust</p><h1>Enterprise Identity</h1><span>Federation, workload certificates and time-bound privileged access.</span></div><button onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></section>{message&&<p className="identity-message">{message}</p>}
 {data&&<><section className="identity-summary"><article><ShieldCheck/><strong>{enterprisePosture(data.summary)}</strong><span>Current posture</span></article><article><Building2/><strong>{data.summary.providers}</strong><span>Enabled providers</span></article><article><KeyRound/><strong>{data.summary.workload_identities}</strong><span>Workload identities</span></article><article><ShieldAlert/><strong>{data.summary.pending_elevations}</strong><span>Pending elevations</span></article></section>
 <section className="identity-grid"><article><header><Building2/><div><strong>OIDC provider</strong><small>Entra ID, Okta, Auth0 or standards-compatible issuer</small></div></header><label>Name<input value={provider.name} onChange={e=>setProvider({...provider,name:e.target.value})}/></label><label>HTTPS issuer<input value={provider.issuer} onChange={e=>setProvider({...provider,issuer:e.target.value})}/></label><label>Client ID<input value={provider.client_id} onChange={e=>setProvider({...provider,client_id:e.target.value})}/></label><label>Allowed domains<input placeholder="example.com, subsidiary.com" value={provider.allowed_domains} onChange={e=>setProvider({...provider,allowed_domains:e.target.value})}/></label><button disabled={!provider.client_id} onClick={()=>void saveProvider()}>Save provider</button></article>
 <article><header><UsersRound/><div><strong>Configured trust</strong><small>Secrets are never stored in this control plane</small></div></header>{data.providers.length?data.providers.map(item=><div className="identity-row" key={item.provider_id}><div><strong>{item.name}</strong><small>{item.issuer}</small></div><span>{item.enabled?"Enabled":"Disabled"}</span></div>):<p>No identity providers configured.</p>}</article></section>
 <section className="identity-panel"><header><ShieldAlert/><div><strong>Temporary privilege elevation</strong><small>Separate-administrator approval and automatic expiry</small></div></header>{data.elevations.length?data.elevations.map(item=><div className="identity-row" key={item.elevation_id}><div><strong>{item.requested_role}</strong><small>{item.reason} · expires {new Date(item.expires_at).toLocaleString()}</small></div><span>{item.status}</span>{item.status==="PENDING"&&<div><button onClick={()=>void decide(item.elevation_id,true)}>Approve</button><button className="danger" onClick={()=>void decide(item.elevation_id,false)}>Reject</button></div>}</div>):<p>No elevation requests recorded.</p>}</section></>}</main>}
