import { useEffect,useState } from "react"
import { KeyRound,RefreshCw,ShieldOff } from "lucide-react"
import { useAuth } from "../context/AuthContext"
import { useToast } from "../context/ToastContext"
import { ConfirmDialog } from "../components/ConfirmDialog"
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncState"
import "../styles/secrets.css"
const API=import.meta.env.VITE_API_BASE_URL??"/api"
type Secret={secret_id:string;name:string;provider:string;reference:string;status:string;created_at:string;last_accessed_at:string|null;access_count:number;rotation_interval_days:number|null;next_rotation_at:string|null}
type Provider={provider:string;available:boolean;credentials_stored:boolean;detail:string}
export default function SecretsPage(){
 const {sessionToken,administrator}=useAuth();const {pushToast}=useToast();const [items,setItems]=useState<Secret[]>([]);const [providers,setProviders]=useState<Provider[]>([]);const [name,setName]=useState("");const [reference,setReference]=useState("");const [provider,setProvider]=useState("ENVIRONMENT");const [rotationDays,setRotationDays]=useState(90);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState("");const [confirmSecret,setConfirmSecret]=useState<Secret|null>(null)
 const headers={"Content-Type":"application/json","x-admin-pin":sessionToken??""}
 const load=async()=>{setLoading(true);setLoadError("");try{const r=await fetch(`${API}/secrets`,{headers});const d=await r.json();if(!r.ok)throw new Error(d.detail);setItems(d.secrets);setProviders(d.providers??[])}catch(e){const detail=e instanceof Error?e.message:"Unable to load secrets.";setLoadError(detail);throw e}finally{setLoading(false)}}
 useEffect(()=>{void load().catch(()=>undefined)},[sessionToken])
 const call=async(path:string,body?:unknown)=>{try{const r=await fetch(`${API}${path}`,{method:"POST",headers,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.detail);pushToast({tone:"success",title:"Secret lifecycle updated",message:"No secret value was exposed or persisted."});setName("");setReference("");setConfirmSecret(null);await load()}catch(e){pushToast({tone:"error",title:"Secret operation failed",message:e instanceof Error?e.message:"Request failed."})}}
 return <main className="secrets-page"><section className="secrets-heading"><div><span>Zero-value exposure</span><h1>Secret lifecycle management</h1><p>GreyGuard stores references and audit evidence only. Secret values are retrieved just in time and never displayed.</p></div><KeyRound size={42}/></section>
 {administrator?.role==="PLATFORM_ADMIN"&&<><section className="secret-create"><input placeholder="Display name" value={name} onChange={e=>setName(e.target.value)}/><select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(p=><option key={p.provider} value={p.provider}>{p.provider}{p.available?"":" (SDK unavailable)"}</option>)}</select><input placeholder={provider==="ENVIRONMENT"?"ENVIRONMENT_VARIABLE":"Provider secret reference"} value={reference} onChange={e=>setReference(provider==="ENVIRONMENT"?e.target.value.toUpperCase():e.target.value)}/><input type="number" min="1" max="365" value={rotationDays} onChange={e=>setRotationDays(Number(e.target.value))}/><button onClick={()=>call("/secrets",{name,reference,provider,rotation_interval_days:rotationDays})}>Register reference</button></section><div className="secret-emergency"><strong>Emergency revocation</strong><span>Immediately revoke every active reference across all providers.</span><button className="danger" onClick={()=>{if(confirm("Revoke every active secret reference?"))void call("/secrets/emergency-revoke",{})}}>Revoke all</button></div></>}
 <section className="secret-grid">{loading&&<LoadingState label="Loading secret references" rows={3}/>} {!loading&&loadError&&<ErrorState message={loadError} onRetry={()=>void load()}/>} {!loading&&!loadError&&items.length===0&&<EmptyState icon={<KeyRound size={30}/>} title="No secret references" description="Register a provider reference without storing its value."/>}{items.map(s=><article key={s.secret_id}><div className="secret-card-head"><KeyRound/><span className={s.status.toLowerCase()}>{s.status}</span></div><h2>{s.name}</h2><code>{s.reference}</code><dl><div><dt>Provider</dt><dd>{s.provider}</dd></div><div><dt>Access count</dt><dd>{s.access_count}</dd></div><div><dt>Last accessed</dt><dd>{s.last_accessed_at??"Never"}</dd></div><div><dt>Next rotation</dt><dd>{s.next_rotation_at??"Not scheduled"}</dd></div></dl>{administrator?.role==="PLATFORM_ADMIN"&&<div className="secret-actions"><button onClick={()=>{const next=prompt("New provider secret reference",s.reference);if(next)void call(`/secrets/${s.secret_id}/rotate`,{reference:next})}}><RefreshCw size={15}/>Rotate</button>{s.status==="ACTIVE"&&<button className="danger" onClick={()=>setConfirmSecret(s)}><ShieldOff size={15}/>Revoke</button>}</div>}</article>)}</section><ConfirmDialog open={Boolean(confirmSecret)} title="Revoke secret reference?" description={`${confirmSecret?.name??"This reference"} will become unavailable to controlled integrations immediately. No secret value will be displayed.`} confirmLabel="Revoke reference" onCancel={()=>setConfirmSecret(null)} onConfirm={()=>confirmSecret&&void call(`/secrets/${confirmSecret.secret_id}/revoke`)}/></main>
}
