import { RadioTower, RefreshCw, Send, ShieldCheck } from "lucide-react"
import { useEffect, useState } from "react"
import { Navigate } from "react-router-dom"
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncState"
import { useAuth } from "../context/AuthContext"
import { useToast } from "../context/ToastContext"
import "../styles/security-exports.css"

const API=import.meta.env.VITE_API_BASE_URL??"/api"
type Destination={destination_id:string;name:string;destination_type:string;endpoint:string;enabled:boolean;minimization_profile:string;rate_limit_per_minute:number;max_attempts:number;last_success_at:string|null;last_failure_at:string|null;last_error:string|null;credentials_stored:boolean}
type ExportRecord={export_id:string;destination_id:string;created_at:string;status:string;attempts:number;event_type:string;delivered_at:string|null;last_error:string|null}
type ExportControl={destinations:Destination[];destination_types:string[];minimization_profiles:string[];summary:{counts:Record<string,number>;recent:ExportRecord[];raw_secrets_exposed:boolean}}
export const destinationHealth=(item:Destination)=>item.last_error?"DEGRADED":item.last_success_at?"HEALTHY":item.enabled?"AWAITING DELIVERY":"DISABLED"

export default function SecurityExportsPage(){
 const {sessionToken,administrator}=useAuth();const {pushToast}=useToast();const [data,setData]=useState<ExportControl|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [name,setName]=useState("");const [type,setType]=useState("SIGNED_WEBHOOK");const [endpoint,setEndpoint]=useState("");const [profile,setProfile]=useState("STANDARD");const [keyReference,setKeyReference]=useState("");const headers={"Content-Type":"application/json","X-Admin-Pin":sessionToken??""}
 const load=async()=>{setLoading(true);setError("");try{const response=await fetch(`${API}/security-exports`,{headers});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Unable to load export controls.");setData(body)}catch(e){setError(e instanceof Error?e.message:"Unable to load export controls.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[sessionToken])
 const save=async()=>{const response=await fetch(`${API}/security-exports/destinations`,{method:"POST",headers,body:JSON.stringify({name,destination_type:type,endpoint,enabled:false,signing_key_reference:keyReference||null,minimization_profile:profile,rate_limit_per_minute:60,max_attempts:5})});const body=await response.json();if(!response.ok){pushToast({tone:"error",title:"Destination rejected",message:body.detail??"Configuration failed."});return}pushToast({tone:"success",title:"Destination registered disabled",message:"Review and explicitly enable it before any evidence can be queued."});setName("");setEndpoint("");setKeyReference("");await load()}
 if(administrator?.role!=="PLATFORM_ADMIN")return <Navigate to="/dashboard" replace/>
 return <main className="security-exports-page"><section className="security-exports-hero"><div><span>Roadmap Section 8</span><h1>Security exports</h1><p>Govern minimized, signed security evidence delivery to approved SIEM and observability destinations.</p></div><button onClick={()=>void load()}><RefreshCw size={17}/>Refresh</button></section><section className="export-boundary"><ShieldCheck/><div><strong>Fail closed by default</strong><span>New destinations are disabled, credentials remain external, and every payload is redacted before queueing.</span></div></section>
 <section className="export-create"><input placeholder="Destination name" value={name} onChange={e=>setName(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}>{(data?.destination_types??[type]).map(item=><option key={item}>{item}</option>)}</select><input placeholder={type==="SYSLOG"?"tls://syslog.example.com:6514":"https://security.example.com/ingest"} value={endpoint} onChange={e=>setEndpoint(e.target.value)}/><select value={profile} onChange={e=>setProfile(e.target.value)}>{(data?.minimization_profiles??[profile]).map(item=><option key={item}>{item}</option>)}</select><input placeholder="Signing key ENV reference (optional)" value={keyReference} onChange={e=>setKeyReference(e.target.value.toUpperCase())}/><button onClick={()=>void save()}><Send size={16}/>Register disabled</button></section>
 {loading&&<LoadingState label="Loading security export controls" rows={3}/>} {!loading&&error&&<ErrorState message={error} onRetry={()=>void load()}/>} {!loading&&!error&&data&&<><section className="export-summary"><article><strong>{data.destinations.length}</strong><span>Destinations</span></article><article><strong>{data.summary.counts.QUEUED??0}</strong><span>Queued</span></article><article><strong>{data.summary.counts.DEAD_LETTER??0}</strong><span>Dead letter</span></article></section><section className="export-grid">{data.destinations.length===0&&<EmptyState icon={<RadioTower/>} title="No export destinations" description="Register an approved destination. It remains disabled until explicitly enabled."/>}{data.destinations.map(item=><article key={item.destination_id}><header><RadioTower/><div><h2>{item.name}</h2><span>{item.destination_type}</span></div><b data-health={destinationHealth(item)}>{destinationHealth(item)}</b></header><code>{item.endpoint}</code><dl><div><dt>Data profile</dt><dd>{item.minimization_profile}</dd></div><div><dt>Rate limit</dt><dd>{item.rate_limit_per_minute}/minute</dd></div><div><dt>Credentials stored</dt><dd>{item.credentials_stored?"Yes":"No"}</dd></div><div><dt>Last success</dt><dd>{item.last_success_at??"Never"}</dd></div></dl>{item.last_error&&<p className="export-error">{item.last_error}</p>}</article>)}</section></>}</main>
}
