"""Drafted assessments for the 30 roadmap threats (October 2026).

Each entry records what GreyGuard actually does today, the residual risk that remains
and the tests that prove the controls. Entries stay NEEDS_REVIEW until a security
reviewer approves them in the Threat Register and sets a review date.
"""

T = "backend/tests/"


def _a(severity, residual, asset, actor, path, controls, evidence, response):
    return {"severity": severity, "residual_risk": residual, "asset": asset, "threat_actor": actor,
            "attack_path": path, "existing_controls": controls,
            "test_evidence": [T + name for name in evidence], "incident_response": response}


ASSESSMENTS = {
    "CREDENTIAL_THEFT": _a("HIGH", "MEDIUM", "Agent credentials and administrator passwords", "External attacker or malware on an agent host",
        "A credential is copied from an agent's configuration, logs or memory and used to impersonate the agent.",
        ["Agent credentials and passwords stored only as salted PBKDF2-SHA256 hashes (310,000 iterations)", "Credential redaction in logs, streams and SDKs", "Credential expiry and rotation", "Scoped service-account keys"],
        ["test_admin_auth.py", "test_service_accounts.py", "test_secret_integrations.py"],
        "Revoke the credential, suspend the agent, review its recent decisions and rotate related secrets."),
    "CREDENTIAL_REPLAY": _a("HIGH", "LOW", "Approval links and administrator sessions", "Attacker who intercepted a previously valid token",
        "A captured approval link or session token is submitted again after it was used or revoked.",
        ["Approval links are single-use and expiring (conditional update on first use)", "Sessions expire and can be revoked"],
        ["test_incident_integrations.py", "test_enterprise_sessions.py"],
        "Revoke affected sessions and links, then review approvals made in the exposure window."),
    "TOKEN_REUSE": _a("HIGH", "LOW", "Administrator refresh tokens", "Attacker holding a stolen refresh token",
        "A stolen refresh token is used after the legitimate client has already rotated it.",
        ["Refresh tokens rotate on every use", "Reuse of a rotated token revokes the whole token family"],
        ["test_enterprise_sessions.py"],
        "Revoke the token family, force re-authentication and investigate the device."),
    "SCOPE_ESCALATION": _a("CRITICAL", "LOW", "Tool execution", "Compromised or misbehaving agent",
        "An agent requests an action outside its registered scope or invents a new action name.",
        ["Every action is checked server-side against the authenticated identity's scopes", "Unknown actions default to BLOCK", "Tools are explicitly allowlisted"],
        ["test_security_foundation.py", "test_agent_sdk.py"],
        "Suspend the agent, review its scope assignment and investigate the source of the request."),
    "CROSS_AGENT_ACCESS": _a("HIGH", "LOW", "Agent evidence and requests", "One agent attempting to act as or observe another",
        "An agent claims another agent's name or filters evidence to read another agent's activity.",
        ["Identity is derived from the credential, never from the claimed name", "Agents have no access to the administrator stream", "Agent filters cannot leak other agents' events"],
        ["test_live_events.py", "test_global_search.py", "test_service_accounts.py"],
        "Suspend both agents, compare authentication evidence and rotate their credentials."),
    "APPROVAL_BYPASS": _a("CRITICAL", "MEDIUM", "Human approval decisions", "Agent or insider avoiding review",
        "A request requiring approval is executed without a valid human decision, or an approval is forged.",
        ["ASK decisions require a human with approval permission", "Approval links are single-use, expiring and signed", "Critical policy changes need a second approver"],
        ["test_incident_integrations.py", "test_policy_governance.py", "test_team_access.py"],
        "Freeze approvals, audit recent decisions and re-review any executed request."),
    "CONFUSED_DEPUTY": _a("HIGH", "MEDIUM", "GreyGuard's own execution authority", "Agent steering GreyGuard to act on its behalf",
        "An agent tricks GreyGuard into using GreyGuard's privileges for an action the agent itself is not allowed to perform.",
        ["GreyGuard executes only allowlisted tools with fixed behaviour inside the sandbox", "The acting agent's scope, not GreyGuard's, authorizes every action"],
        ["test_security_foundation.py", "test_agent_sdk.py"],
        "Disable the affected tool, review its recent executions and tighten its parameters."),
    "PROMPT_INJECTION": _a("HIGH", "HIGH", "Agent decision-making", "Attacker-controlled content read by an agent's model",
        "Injected instructions change what the agent requests. GreyGuard cannot see the model's prompt, so it cannot detect the injection itself.",
        ["Every resulting tool call is still evaluated by policy and scope", "Risk scoring accumulates and auto-suspends agents", "Sensitive actions require human approval"],
        ["test_security_foundation.py", "test_policy_governance.py"],
        "Suspend the agent, identify the injected source and add a blocking policy for the abused action."),
    "MALICIOUS_TOOL_OUTPUT": _a("MEDIUM", "MEDIUM", "Data returned to agents", "Attacker who planted content in sandbox files",
        "A tool returns attacker-planted content that misleads the agent's next steps.",
        ["Tool output is size-limited and returned as data, never executed", "Sandbox file access only"],
        ["test_security_foundation.py"],
        "Quarantine the planted content and review the agent's subsequent requests."),
    "PATH_TRAVERSAL": _a("HIGH", "LOW", "Host filesystem", "Agent supplying crafted file paths",
        "An agent supplies ../ sequences or absolute paths to reach files outside the sandbox.",
        ["Absolute paths are rejected", "Paths are resolved and must stay inside the sandbox root"],
        ["test_security_foundation.py"],
        "Suspend the agent and verify no file outside the sandbox was read."),
    "SYMLINK_ESCAPE": _a("HIGH", "LOW", "Host filesystem", "Agent or attacker able to place links in the sandbox",
        "A symbolic link inside the sandbox points outside it and is followed by a tool.",
        ["Targets are resolved through symbolic links before the sandbox-containment check"],
        ["test_symlink_escape.py"],
        "Remove the link, suspend the agent and verify no outside file was read."),
    "SANDBOX_ESCAPE": _a("CRITICAL", "MEDIUM", "Execution host", "Malicious workload inside the controlled sandbox",
        "Code in the Docker sandbox exploits the container runtime or kernel to reach the host.",
        ["Disabled by default; only predefined jobs", "No network, read-only filesystem, non-root user, all capabilities dropped, no-new-privileges", "Seccomp profile and CPU, memory and process limits", "Emergency termination across all workers"],
        ["test_execution_isolation.py", "test_isolation_operations.py"],
        "Trigger emergency termination, isolate the host and rebuild it from a known-good image."),
    "SERVER_SIDE_REQUEST_FORGERY": _a("HIGH", "HIGH", "Internal network services", "Administrator account misuse or compromised administrator",
        "An integration destination URL points at an internal service, so GreyGuard sends requests into the internal network.",
        ["Destinations are configured only by administrators", "Sandbox network is disabled or destination-allowlisted", "GAP: outbound integrations do not yet block private or link-local addresses"],
        ["test_security_exports.py", "test_notification_delivery.py"],
        "Disable the integration, review its destination history and add private-address blocking."),
    "COMMAND_INJECTION": _a("CRITICAL", "LOW", "Execution host", "Agent supplying crafted input",
        "Input reaches a shell and runs attacker-chosen commands.",
        ["No shell execution anywhere; fixed argument lists only", "Sandbox runs predefined jobs, never agent-supplied commands"],
        ["test_operational_assurance.py", "test_assurance_matrix.py", "test_execution_isolation.py"],
        "Disable execution, review execution history and audit the code path."),
    "SQL_INJECTION": _a("HIGH", "LOW", "GreyGuard database", "External attacker or agent supplying crafted input",
        "Input is concatenated into SQL and alters a query.",
        ["Parameterized queries throughout", "Static analysis in the release gate"],
        ["test_database_compatibility.py", "test_final_security_review.py"],
        "Restore from a verified backup if data changed and fix the query."),
    "CROSS_SITE_SCRIPTING": _a("HIGH", "MEDIUM", "Administrator sessions in the browser", "Attacker who gets content displayed in the console",
        "Malicious script in displayed evidence runs in an administrator's browser and steals the session token from session storage.",
        ["React escapes all rendered content; no raw HTML injection anywhere in the frontend", "X-Content-Type-Options, X-Frame-Options and Referrer-Policy headers", "GAP: no Content-Security-Policy header yet"],
        ["test_api_compatibility.py"],
        "Revoke all administrator sessions, find the stored payload and remove it."),
    "CROSS_SITE_REQUEST_FORGERY": _a("MEDIUM", "LOW", "Administrator actions", "Malicious website visited by an administrator",
        "Another website causes the administrator's browser to send a state-changing request to GreyGuard.",
        ["Authentication uses a custom request header, which browsers never attach automatically", "CORS allowlist; no cookie-based authentication"],
        ["test_security_foundation.py", "test_runtime_security.py"],
        "Revoke sessions and review administrator actions in the affected window."),
    "INSECURE_DIRECT_OBJECT_REFERENCE": _a("HIGH", "MEDIUM", "Records addressed by ID", "Authenticated user with a lower role",
        "A user changes an ID in a request to read or change a record they should not reach.",
        ["Every protected route requires authentication and a role permission", "Single organization today; per-tenant isolation arrives in Phase C"],
        ["test_team_access.py", "test_service_accounts.py"],
        "Review access logs for the affected records and correct the permission check."),
    "SENSITIVE_DATA_LEAKAGE": _a("HIGH", "MEDIUM", "Secrets and personal data in evidence", "Anyone with access to logs, exports or streams",
        "Secrets or personal data appear in logs, telemetry, exports or the live stream.",
        ["Secret-redaction middleware", "Recursive redaction in telemetry, streams and SDKs", "Per-destination data minimization for exports"],
        ["test_observability.py", "test_live_events.py", "test_python_sdk.py", "test_secret_integrations.py"],
        "Rotate exposed secrets, purge affected exports and fix the redaction gap."),
    "AUDIT_LOG_TAMPERING": _a("HIGH", "MEDIUM", "Audit evidence", "Insider or attacker with database access",
        "Audit records are altered or deleted to hide activity.",
        ["Tamper-evident hash chaining with integrity verification", "Retention, immutable-retention and legal-hold options", "Residual: a database administrator could rewrite the whole chain unless it is exported or anchored externally"],
        ["test_audit_integrity.py"],
        "Verify the chain, compare with exported copies and restore from backup."),
    "RACE_DOUBLE_EXECUTION": _a("HIGH", "MEDIUM", "Approvals and tool executions", "Concurrent clients or retrying agents",
        "The same request is approved or executed twice through concurrent or repeated submissions.",
        ["Single-use approvals via conditional updates", "SDK idempotency keys", "Serialized database startup across workers"],
        ["test_python_sdk.py", "test_incident_integrations.py", "test_postgres_startup_safety.py"],
        "Identify duplicate executions in evidence and reverse their effects."),
    "DENIAL_OF_SERVICE": _a("MEDIUM", "MEDIUM", "GreyGuard availability", "External attacker or runaway agent",
        "Request floods or heavy workloads exhaust GreyGuard's capacity.",
        ["Per-category rate limiting and login lockout", "2 MB request-body limit at the proxy", "Bounded stream buffers and sandbox resource limits"],
        ["test_abuse_protection.py", "test_live_events.py"],
        "Block the source, tighten rate limits and scale or restart services."),
    "DEPENDENCY_COMPROMISE": _a("HIGH", "MEDIUM", "Build and runtime supply chain", "Compromised third-party package or image",
        "A malicious or vulnerable dependency is included in a GreyGuard release.",
        ["pip-audit and npm audit in the release gate", "CycloneDX SBOM generation and verification", "Container scanning of both images", "Signed releases"],
        ["test_final_security_review.py", "test_release_operations.py", "test_operational_assurance.py"],
        "Pin or remove the dependency, rebuild, rescan and issue a signed release."),
    "MALICIOUS_INTEGRATION_WEBHOOK": _a("MEDIUM", "MEDIUM", "Outbound and inbound integrations", "Compromised integration endpoint",
        "A webhook destination or callback is malicious and abuses GreyGuard's data or callbacks.",
        ["HMAC-signed webhooks and callbacks", "HTTPS destinations", "Per-integration disable switches"],
        ["test_security_exports.py", "test_incident_integrations.py", "test_notification_delivery.py"],
        "Disable the integration, rotate its signing secret and review what it received."),
    "EXCESSIVE_DATA_RETENTION": _a("MEDIUM", "LOW", "Stored evidence and notifications", "Privacy and compliance exposure",
        "Data is kept longer than needed, increasing breach impact and legal exposure.",
        ["Configurable retention and deletion", "Notification retention controls"],
        ["test_audit_integrity.py", "test_notifications.py"],
        "Apply retention, confirm deletion and document the exception."),
    "MISCONFIGURED_ADMIN_CAPABILITY": _a("HIGH", "MEDIUM", "High-impact capabilities", "Administrator error",
        "A powerful capability is enabled too broadly or left on.",
        ["Universal controls: disabled by default, named owner, purpose, expiry and allowlists", "Production configuration validated fail-closed", "Shared PIN forbidden in production"],
        ["test_universal_controls.py", "test_production_readiness.py", "test_legacy_pin_production.py"],
        "Disable the capability, review its use and correct the configuration."),
    "INSIDER_MISUSE": _a("HIGH", "MEDIUM", "Administrative authority", "Malicious or coerced administrator",
        "An administrator abuses legitimate access.",
        ["Role separation", "Four-eyes approval for critical policy changes", "Time-limited elevation and audited break-glass"],
        ["test_team_access.py", "test_enterprise_identity.py", "test_policy_governance.py"],
        "Revoke access, preserve evidence and escalate under the incident process."),
    "UNSAFE_AUTOMATIC_RESPONSE": _a("MEDIUM", "MEDIUM", "Systems affected by defensive actions", "Faulty detection or attacker triggering responses",
        "An automatic defensive action disrupts legitimate work.",
        ["Responses require human approval", "Responses expire automatically", "Recoverable quarantine and rollback"],
        ["test_defensive_integrations.py"],
        "Roll back the response and review the triggering evidence."),
    "KILL_SWITCH_FAILURE": _a("CRITICAL", "LOW", "Emergency containment", "Any active incident",
        "The emergency stop fails to stop agents, tools or sandbox jobs.",
        ["Global deny, per-agent and per-tool disable", "Sandbox termination driven by the database, so it works across all workers"],
        ["test_execution_isolation.py", "test_capability_removal.py", "test_isolation_operations.py"],
        "Stop the backend services and isolate the host manually."),
    "BACKUP_RECOVERY_FAILURE": _a("HIGH", "LOW", "GreyGuard data", "Operational failure or ransomware",
        "Backups are missing, corrupt or cannot be restored when needed.",
        ["Encrypted backups with checksums", "Verified restore that requires confirmation", "Rehearsed migration and production recovery"],
        ["test_production_readiness.py", "test_deployment_operations.py", "test_pre_final_hardening.py"],
        "Restore from the last verified backup and repeat the recovery rehearsal."),
}
